### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Jstunkard** [Jstunkard/spaceroids#1]
- [ ] health bar in addition to lives
- [ ] show current level in window
- [ ] create a status bar overlay to store health, lives, score, and level

**Comment by seven1m** [comment]
:+1:
